DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER`
(
   `ID`        INT          NOT NULL AUTO_INCREMENT,
   `USER_NAME` VARCHAR(100) NOT NULL ,
   `PASSWORD`  VARCHAR(200) NOT NULL ,
   `EMAIL`     VARCHAR(100) NOT NULL ,

   PRIMARY KEY (`ID`)
);
